version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
    container_name: elasticsearch
    command: bin/elasticsearch -Ecluster.name=myes -Ehttp.port=9200 -Ehttp.cors.allow-origin="*" -Ehttp.cors.enabled=true -Ehttp.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization,Access-Control-Allow-Origin -Ehttp.cors.allow-credentials=true
    environment:
      ES_JAVA_OPTS: "-Xms2048m -Xmx2048m"
    ports:
     - "9200:9200"
     - "9300:9300"

  dejavu:
    image: appbaseio/dejavu:latest
    container_name: dejavu
    ports:
     - "1358:1358"
    links:
      - elasticsearch

  elastichq:
    build: docker/elastichq-docker
    container_name: elastichq
    ports:
     - "80:80"
    links:
      - elasticsearch
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:5.6.8
#    container_name: kibana
#    links:
#      - elasticsearch:elasticsearch
#    environment:
#      SERVER_NAME: kibana.local
#      ELASTICSEARCH_URL: http://elasticsearch
#    ports: ['5601:5601']

  graphana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    links:
      - elasticsearch:elasticsearch
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel
